/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Float = number;
export interface Investment {
  'folioNumber' : [] | [string],
  'isSEBIRegistered' : boolean,
  'name' : string,
  'currentValue' : Float,
  'notes' : [] | [string],
  'category' : InvestmentCategory,
  'amountInvested' : Float,
  'dateOfInvestment' : Time,
}
export type InvestmentCategory = { 'cryptocurrency' : null } |
  { 'mutualFunds' : null } |
  { 'stocks' : null } |
  { 'unitLinkedInsurancePlans' : null } |
  { 'pensionPrivate' : null } |
  { 'postOfficeSchemes' : null } |
  { 'seniorCitizenSavingsScheme' : null } |
  { 'other' : null } |
  { 'fixedDepositsNationalized' : null } |
  { 'chits' : null } |
  { 'fixedDepositsCorporate' : null } |
  { 'sebiRegisteredCompanies' : null } |
  { 'silverBonds' : null } |
  { 'nationalSavings' : null } |
  { 'sovereignGoldBonds' : null } |
  { 'realEstateInvestmentTrusts' : null } |
  { 'insuranceAsset' : null } |
  { 'bonds' : null } |
  { 'insuranceWealth' : null } |
  { 'insuranceHealth' : null } |
  { 'equity' : null } |
  { 'nationalPensionSystem' : null } |
  { 'liquidityHoldings' : null } |
  { 'debtFunds' : null } |
  { 'publicProvidentFund' : null };
export interface Nominee {
  'contactInfo' : string,
  'name' : string,
  'nomineePrincipal' : Principal,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'permanentAddress' : string,
  'temporaryAddress' : string,
  'panNumber' : [] | [string],
  'aadhaarNumber' : [] | [string],
  'contactNumbers' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInvestment' : ActorMethod<[Investment], undefined>,
  'addNominee' : ActorMethod<[Nominee], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteInvestment' : ActorMethod<[bigint], undefined>,
  'fetchAadhaarDetails' : ActorMethod<[], string>,
  'fetchPanDetails' : ActorMethod<[], string>,
  'fetchSoaHoldings' : ActorMethod<[], string>,
  'getCallerNominee' : ActorMethod<[], [] | [Nominee]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestments' : ActorMethod<[Principal], Array<Investment>>,
  'getNominee' : ActorMethod<[Principal], [] | [Nominee]>,
  'getTotalInvestmentSummary' : ActorMethod<
    [Principal],
    { 'totalInvested' : number, 'totalCurrentValue' : number }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeNominee' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateInvestment' : ActorMethod<[bigint, Investment], undefined>,
  'updateNominee' : ActorMethod<[Nominee], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];