/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Float = IDL.Float64;
export const InvestmentCategory = IDL.Variant({
  'cryptocurrency' : IDL.Null,
  'mutualFunds' : IDL.Null,
  'stocks' : IDL.Null,
  'unitLinkedInsurancePlans' : IDL.Null,
  'pensionPrivate' : IDL.Null,
  'postOfficeSchemes' : IDL.Null,
  'seniorCitizenSavingsScheme' : IDL.Null,
  'other' : IDL.Null,
  'fixedDepositsNationalized' : IDL.Null,
  'chits' : IDL.Null,
  'fixedDepositsCorporate' : IDL.Null,
  'sebiRegisteredCompanies' : IDL.Null,
  'silverBonds' : IDL.Null,
  'nationalSavings' : IDL.Null,
  'sovereignGoldBonds' : IDL.Null,
  'realEstateInvestmentTrusts' : IDL.Null,
  'insuranceAsset' : IDL.Null,
  'bonds' : IDL.Null,
  'insuranceWealth' : IDL.Null,
  'insuranceHealth' : IDL.Null,
  'equity' : IDL.Null,
  'nationalPensionSystem' : IDL.Null,
  'liquidityHoldings' : IDL.Null,
  'debtFunds' : IDL.Null,
  'publicProvidentFund' : IDL.Null,
});
export const Time = IDL.Int;
export const Investment = IDL.Record({
  'folioNumber' : IDL.Opt(IDL.Text),
  'isSEBIRegistered' : IDL.Bool,
  'name' : IDL.Text,
  'currentValue' : Float,
  'notes' : IDL.Opt(IDL.Text),
  'category' : InvestmentCategory,
  'amountInvested' : Float,
  'dateOfInvestment' : Time,
});
export const Nominee = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'nomineePrincipal' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'permanentAddress' : IDL.Text,
  'temporaryAddress' : IDL.Text,
  'panNumber' : IDL.Opt(IDL.Text),
  'aadhaarNumber' : IDL.Opt(IDL.Text),
  'contactNumbers' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInvestment' : IDL.Func([Investment], [], []),
  'addNominee' : IDL.Func([Nominee], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
  'fetchAadhaarDetails' : IDL.Func([], [IDL.Text], []),
  'fetchPanDetails' : IDL.Func([], [IDL.Text], []),
  'fetchSoaHoldings' : IDL.Func([], [IDL.Text], []),
  'getCallerNominee' : IDL.Func([], [IDL.Opt(Nominee)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Investment)],
      ['query'],
    ),
  'getNominee' : IDL.Func([IDL.Principal], [IDL.Opt(Nominee)], ['query']),
  'getTotalInvestmentSummary' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'totalInvested' : IDL.Float64,
          'totalCurrentValue' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeNominee' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateInvestment' : IDL.Func([IDL.Nat, Investment], [], []),
  'updateNominee' : IDL.Func([Nominee], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Float = IDL.Float64;
  const InvestmentCategory = IDL.Variant({
    'cryptocurrency' : IDL.Null,
    'mutualFunds' : IDL.Null,
    'stocks' : IDL.Null,
    'unitLinkedInsurancePlans' : IDL.Null,
    'pensionPrivate' : IDL.Null,
    'postOfficeSchemes' : IDL.Null,
    'seniorCitizenSavingsScheme' : IDL.Null,
    'other' : IDL.Null,
    'fixedDepositsNationalized' : IDL.Null,
    'chits' : IDL.Null,
    'fixedDepositsCorporate' : IDL.Null,
    'sebiRegisteredCompanies' : IDL.Null,
    'silverBonds' : IDL.Null,
    'nationalSavings' : IDL.Null,
    'sovereignGoldBonds' : IDL.Null,
    'realEstateInvestmentTrusts' : IDL.Null,
    'insuranceAsset' : IDL.Null,
    'bonds' : IDL.Null,
    'insuranceWealth' : IDL.Null,
    'insuranceHealth' : IDL.Null,
    'equity' : IDL.Null,
    'nationalPensionSystem' : IDL.Null,
    'liquidityHoldings' : IDL.Null,
    'debtFunds' : IDL.Null,
    'publicProvidentFund' : IDL.Null,
  });
  const Time = IDL.Int;
  const Investment = IDL.Record({
    'folioNumber' : IDL.Opt(IDL.Text),
    'isSEBIRegistered' : IDL.Bool,
    'name' : IDL.Text,
    'currentValue' : Float,
    'notes' : IDL.Opt(IDL.Text),
    'category' : InvestmentCategory,
    'amountInvested' : Float,
    'dateOfInvestment' : Time,
  });
  const Nominee = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'nomineePrincipal' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'permanentAddress' : IDL.Text,
    'temporaryAddress' : IDL.Text,
    'panNumber' : IDL.Opt(IDL.Text),
    'aadhaarNumber' : IDL.Opt(IDL.Text),
    'contactNumbers' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInvestment' : IDL.Func([Investment], [], []),
    'addNominee' : IDL.Func([Nominee], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
    'fetchAadhaarDetails' : IDL.Func([], [IDL.Text], []),
    'fetchPanDetails' : IDL.Func([], [IDL.Text], []),
    'fetchSoaHoldings' : IDL.Func([], [IDL.Text], []),
    'getCallerNominee' : IDL.Func([], [IDL.Opt(Nominee)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Investment)],
        ['query'],
      ),
    'getNominee' : IDL.Func([IDL.Principal], [IDL.Opt(Nominee)], ['query']),
    'getTotalInvestmentSummary' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'totalInvested' : IDL.Float64,
            'totalCurrentValue' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeNominee' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateInvestment' : IDL.Func([IDL.Nat, Investment], [], []),
    'updateNominee' : IDL.Func([Nominee], [], []),
  });
};

export const init = ({ IDL }) => { return []; };