/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Nominee {
    contactInfo: string;
    name: string;
    nomineePrincipal: Principal;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Investment {
    folioNumber?: string;
    isSEBIRegistered: boolean;
    name: string;
    currentValue: Float;
    notes?: string;
    category: InvestmentCategory;
    amountInvested: Float;
    dateOfInvestment: Time;
}
export type Float = number;
export interface UserProfile {
    permanentAddress: string;
    temporaryAddress: string;
    panNumber?: string;
    aadhaarNumber?: string;
    contactNumbers: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export enum InvestmentCategory {
    cryptocurrency = "cryptocurrency",
    mutualFunds = "mutualFunds",
    stocks = "stocks",
    unitLinkedInsurancePlans = "unitLinkedInsurancePlans",
    pensionPrivate = "pensionPrivate",
    postOfficeSchemes = "postOfficeSchemes",
    seniorCitizenSavingsScheme = "seniorCitizenSavingsScheme",
    other = "other",
    fixedDepositsNationalized = "fixedDepositsNationalized",
    chits = "chits",
    fixedDepositsCorporate = "fixedDepositsCorporate",
    sebiRegisteredCompanies = "sebiRegisteredCompanies",
    silverBonds = "silverBonds",
    nationalSavings = "nationalSavings",
    sovereignGoldBonds = "sovereignGoldBonds",
    realEstateInvestmentTrusts = "realEstateInvestmentTrusts",
    insuranceAsset = "insuranceAsset",
    bonds = "bonds",
    insuranceWealth = "insuranceWealth",
    insuranceHealth = "insuranceHealth",
    equity = "equity",
    nationalPensionSystem = "nationalPensionSystem",
    liquidityHoldings = "liquidityHoldings",
    debtFunds = "debtFunds",
    publicProvidentFund = "publicProvidentFund"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInvestment(investment: Investment): Promise<void>;
    addNominee(nominee: Nominee): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteInvestment(index: bigint): Promise<void>;
    fetchAadhaarDetails(): Promise<string>;
    fetchPanDetails(): Promise<string>;
    fetchSoaHoldings(): Promise<string>;
    getCallerNominee(): Promise<Nominee | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvestments(user: Principal): Promise<Array<Investment>>;
    getNominee(user: Principal): Promise<Nominee | null>;
    getTotalInvestmentSummary(user: Principal): Promise<{
        totalInvested: number;
        totalCurrentValue: number;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeNominee(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateInvestment(index: bigint, investment: Investment): Promise<void>;
    updateNominee(nominee: Nominee): Promise<void>;
}
import type { Float as _Float, Investment as _Investment, InvestmentCategory as _InvestmentCategory, Nominee as _Nominee, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInvestment(arg0: Investment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvestment(to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvestment(to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNominee(arg0: Nominee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNominee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNominee(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteInvestment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvestment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvestment(arg0);
            return result;
        }
    }
    async fetchAadhaarDetails(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAadhaarDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAadhaarDetails();
            return result;
        }
    }
    async fetchPanDetails(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPanDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPanDetails();
            return result;
        }
    }
    async fetchSoaHoldings(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSoaHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSoaHoldings();
            return result;
        }
    }
    async getCallerNominee(): Promise<Nominee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNominee();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNominee();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestments(arg0: Principal): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestments(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestments(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNominee(arg0: Principal): Promise<Nominee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNominee(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNominee(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalInvestmentSummary(arg0: Principal): Promise<{
        totalInvested: number;
        totalCurrentValue: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalInvestmentSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalInvestmentSummary(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeNominee(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNominee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNominee();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateInvestment(arg0: bigint, arg1: Investment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvestment(arg0, to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvestment(arg0, to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNominee(arg0: Nominee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNominee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNominee(arg0);
            return result;
        }
    }
}
function from_candid_InvestmentCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentCategory): InvestmentCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Investment_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Investment): Investment {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Nominee]): Nominee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permanentAddress: string;
    temporaryAddress: string;
    panNumber: [] | [string];
    aadhaarNumber: [] | [string];
    contactNumbers: Array<string>;
}): {
    permanentAddress: string;
    temporaryAddress: string;
    panNumber?: string;
    aadhaarNumber?: string;
    contactNumbers: Array<string>;
} {
    return {
        permanentAddress: value.permanentAddress,
        temporaryAddress: value.temporaryAddress,
        panNumber: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.panNumber)),
        aadhaarNumber: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.aadhaarNumber)),
        contactNumbers: value.contactNumbers
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    folioNumber: [] | [string];
    isSEBIRegistered: boolean;
    name: string;
    currentValue: _Float;
    notes: [] | [string];
    category: _InvestmentCategory;
    amountInvested: _Float;
    dateOfInvestment: _Time;
}): {
    folioNumber?: string;
    isSEBIRegistered: boolean;
    name: string;
    currentValue: Float;
    notes?: string;
    category: InvestmentCategory;
    amountInvested: Float;
    dateOfInvestment: Time;
} {
    return {
        folioNumber: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.folioNumber)),
        isSEBIRegistered: value.isSEBIRegistered,
        name: value.name,
        currentValue: value.currentValue,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_InvestmentCategory_n17(_uploadFile, _downloadFile, value.category),
        amountInvested: value.amountInvested,
        dateOfInvestment: value.dateOfInvestment
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cryptocurrency: null;
} | {
    mutualFunds: null;
} | {
    stocks: null;
} | {
    unitLinkedInsurancePlans: null;
} | {
    pensionPrivate: null;
} | {
    postOfficeSchemes: null;
} | {
    seniorCitizenSavingsScheme: null;
} | {
    other: null;
} | {
    fixedDepositsNationalized: null;
} | {
    chits: null;
} | {
    fixedDepositsCorporate: null;
} | {
    sebiRegisteredCompanies: null;
} | {
    silverBonds: null;
} | {
    nationalSavings: null;
} | {
    sovereignGoldBonds: null;
} | {
    realEstateInvestmentTrusts: null;
} | {
    insuranceAsset: null;
} | {
    bonds: null;
} | {
    insuranceWealth: null;
} | {
    insuranceHealth: null;
} | {
    equity: null;
} | {
    nationalPensionSystem: null;
} | {
    liquidityHoldings: null;
} | {
    debtFunds: null;
} | {
    publicProvidentFund: null;
}): InvestmentCategory {
    return "cryptocurrency" in value ? InvestmentCategory.cryptocurrency : "mutualFunds" in value ? InvestmentCategory.mutualFunds : "stocks" in value ? InvestmentCategory.stocks : "unitLinkedInsurancePlans" in value ? InvestmentCategory.unitLinkedInsurancePlans : "pensionPrivate" in value ? InvestmentCategory.pensionPrivate : "postOfficeSchemes" in value ? InvestmentCategory.postOfficeSchemes : "seniorCitizenSavingsScheme" in value ? InvestmentCategory.seniorCitizenSavingsScheme : "other" in value ? InvestmentCategory.other : "fixedDepositsNationalized" in value ? InvestmentCategory.fixedDepositsNationalized : "chits" in value ? InvestmentCategory.chits : "fixedDepositsCorporate" in value ? InvestmentCategory.fixedDepositsCorporate : "sebiRegisteredCompanies" in value ? InvestmentCategory.sebiRegisteredCompanies : "silverBonds" in value ? InvestmentCategory.silverBonds : "nationalSavings" in value ? InvestmentCategory.nationalSavings : "sovereignGoldBonds" in value ? InvestmentCategory.sovereignGoldBonds : "realEstateInvestmentTrusts" in value ? InvestmentCategory.realEstateInvestmentTrusts : "insuranceAsset" in value ? InvestmentCategory.insuranceAsset : "bonds" in value ? InvestmentCategory.bonds : "insuranceWealth" in value ? InvestmentCategory.insuranceWealth : "insuranceHealth" in value ? InvestmentCategory.insuranceHealth : "equity" in value ? InvestmentCategory.equity : "nationalPensionSystem" in value ? InvestmentCategory.nationalPensionSystem : "liquidityHoldings" in value ? InvestmentCategory.liquidityHoldings : "debtFunds" in value ? InvestmentCategory.debtFunds : "publicProvidentFund" in value ? InvestmentCategory.publicProvidentFund : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Investment>): Array<Investment> {
    return value.map((x)=>from_candid_Investment_n15(_uploadFile, _downloadFile, x));
}
function to_candid_InvestmentCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentCategory): _InvestmentCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Investment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Investment): _Investment {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    folioNumber?: string;
    isSEBIRegistered: boolean;
    name: string;
    currentValue: Float;
    notes?: string;
    category: InvestmentCategory;
    amountInvested: Float;
    dateOfInvestment: Time;
}): {
    folioNumber: [] | [string];
    isSEBIRegistered: boolean;
    name: string;
    currentValue: _Float;
    notes: [] | [string];
    category: _InvestmentCategory;
    amountInvested: _Float;
    dateOfInvestment: _Time;
} {
    return {
        folioNumber: value.folioNumber ? candid_some(value.folioNumber) : candid_none(),
        isSEBIRegistered: value.isSEBIRegistered,
        name: value.name,
        currentValue: value.currentValue,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_InvestmentCategory_n3(_uploadFile, _downloadFile, value.category),
        amountInvested: value.amountInvested,
        dateOfInvestment: value.dateOfInvestment
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permanentAddress: string;
    temporaryAddress: string;
    panNumber?: string;
    aadhaarNumber?: string;
    contactNumbers: Array<string>;
}): {
    permanentAddress: string;
    temporaryAddress: string;
    panNumber: [] | [string];
    aadhaarNumber: [] | [string];
    contactNumbers: Array<string>;
} {
    return {
        permanentAddress: value.permanentAddress,
        temporaryAddress: value.temporaryAddress,
        panNumber: value.panNumber ? candid_some(value.panNumber) : candid_none(),
        aadhaarNumber: value.aadhaarNumber ? candid_some(value.aadhaarNumber) : candid_none(),
        contactNumbers: value.contactNumbers
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentCategory): {
    cryptocurrency: null;
} | {
    mutualFunds: null;
} | {
    stocks: null;
} | {
    unitLinkedInsurancePlans: null;
} | {
    pensionPrivate: null;
} | {
    postOfficeSchemes: null;
} | {
    seniorCitizenSavingsScheme: null;
} | {
    other: null;
} | {
    fixedDepositsNationalized: null;
} | {
    chits: null;
} | {
    fixedDepositsCorporate: null;
} | {
    sebiRegisteredCompanies: null;
} | {
    silverBonds: null;
} | {
    nationalSavings: null;
} | {
    sovereignGoldBonds: null;
} | {
    realEstateInvestmentTrusts: null;
} | {
    insuranceAsset: null;
} | {
    bonds: null;
} | {
    insuranceWealth: null;
} | {
    insuranceHealth: null;
} | {
    equity: null;
} | {
    nationalPensionSystem: null;
} | {
    liquidityHoldings: null;
} | {
    debtFunds: null;
} | {
    publicProvidentFund: null;
} {
    return value == InvestmentCategory.cryptocurrency ? {
        cryptocurrency: null
    } : value == InvestmentCategory.mutualFunds ? {
        mutualFunds: null
    } : value == InvestmentCategory.stocks ? {
        stocks: null
    } : value == InvestmentCategory.unitLinkedInsurancePlans ? {
        unitLinkedInsurancePlans: null
    } : value == InvestmentCategory.pensionPrivate ? {
        pensionPrivate: null
    } : value == InvestmentCategory.postOfficeSchemes ? {
        postOfficeSchemes: null
    } : value == InvestmentCategory.seniorCitizenSavingsScheme ? {
        seniorCitizenSavingsScheme: null
    } : value == InvestmentCategory.other ? {
        other: null
    } : value == InvestmentCategory.fixedDepositsNationalized ? {
        fixedDepositsNationalized: null
    } : value == InvestmentCategory.chits ? {
        chits: null
    } : value == InvestmentCategory.fixedDepositsCorporate ? {
        fixedDepositsCorporate: null
    } : value == InvestmentCategory.sebiRegisteredCompanies ? {
        sebiRegisteredCompanies: null
    } : value == InvestmentCategory.silverBonds ? {
        silverBonds: null
    } : value == InvestmentCategory.nationalSavings ? {
        nationalSavings: null
    } : value == InvestmentCategory.sovereignGoldBonds ? {
        sovereignGoldBonds: null
    } : value == InvestmentCategory.realEstateInvestmentTrusts ? {
        realEstateInvestmentTrusts: null
    } : value == InvestmentCategory.insuranceAsset ? {
        insuranceAsset: null
    } : value == InvestmentCategory.bonds ? {
        bonds: null
    } : value == InvestmentCategory.insuranceWealth ? {
        insuranceWealth: null
    } : value == InvestmentCategory.insuranceHealth ? {
        insuranceHealth: null
    } : value == InvestmentCategory.equity ? {
        equity: null
    } : value == InvestmentCategory.nationalPensionSystem ? {
        nationalPensionSystem: null
    } : value == InvestmentCategory.liquidityHoldings ? {
        liquidityHoldings: null
    } : value == InvestmentCategory.debtFunds ? {
        debtFunds: null
    } : value == InvestmentCategory.publicProvidentFund ? {
        publicProvidentFund: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
